/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WithdrawRouteImport } from './routes/withdraw'
import { Route as WingoRouteImport } from './routes/wingo'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VipRouteImport } from './routes/vip'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PromotionRouteImport } from './routes/promotion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DepositRouteImport } from './routes/deposit'
import { Route as AviatorRouteImport } from './routes/aviator'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'

const WithdrawRoute = WithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => rootRouteImport,
} as any)
const WingoRoute = WingoRouteImport.update({
  id: '/wingo',
  path: '/wingo',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VipRoute = VipRouteImport.update({
  id: '/vip',
  path: '/vip',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PromotionRoute = PromotionRouteImport.update({
  id: '/promotion',
  path: '/promotion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositRoute = DepositRouteImport.update({
  id: '/deposit',
  path: '/deposit',
  getParentRoute: () => rootRouteImport,
} as any)
const AviatorRoute = AviatorRouteImport.update({
  id: '/aviator',
  path: '/aviator',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/aviator': typeof AviatorRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/promotion': typeof PromotionRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/wingo': typeof WingoRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/aviator': typeof AviatorRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/promotion': typeof PromotionRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/wingo': typeof WingoRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/activity': typeof ActivityRoute
  '/aviator': typeof AviatorRoute
  '/deposit': typeof DepositRoute
  '/login': typeof LoginRoute
  '/promotion': typeof PromotionRoute
  '/register': typeof RegisterRoute
  '/vip': typeof VipRoute
  '/wallet': typeof WalletRoute
  '/wingo': typeof WingoRoute
  '/withdraw': typeof WithdrawRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/activity'
    | '/aviator'
    | '/deposit'
    | '/login'
    | '/promotion'
    | '/register'
    | '/vip'
    | '/wallet'
    | '/wingo'
    | '/withdraw'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/activity'
    | '/aviator'
    | '/deposit'
    | '/login'
    | '/promotion'
    | '/register'
    | '/vip'
    | '/wallet'
    | '/wingo'
    | '/withdraw'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/activity'
    | '/aviator'
    | '/deposit'
    | '/login'
    | '/promotion'
    | '/register'
    | '/vip'
    | '/wallet'
    | '/wingo'
    | '/withdraw'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  ActivityRoute: typeof ActivityRoute
  AviatorRoute: typeof AviatorRoute
  DepositRoute: typeof DepositRoute
  LoginRoute: typeof LoginRoute
  PromotionRoute: typeof PromotionRoute
  RegisterRoute: typeof RegisterRoute
  VipRoute: typeof VipRoute
  WalletRoute: typeof WalletRoute
  WingoRoute: typeof WingoRoute
  WithdrawRoute: typeof WithdrawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/withdraw': {
      id: '/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof WithdrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wingo': {
      id: '/wingo'
      path: '/wingo'
      fullPath: '/wingo'
      preLoaderRoute: typeof WingoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip': {
      id: '/vip'
      path: '/vip'
      fullPath: '/vip'
      preLoaderRoute: typeof VipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promotion': {
      id: '/promotion'
      path: '/promotion'
      fullPath: '/promotion'
      preLoaderRoute: typeof PromotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposit': {
      id: '/deposit'
      path: '/deposit'
      fullPath: '/deposit'
      preLoaderRoute: typeof DepositRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aviator': {
      id: '/aviator'
      path: '/aviator'
      fullPath: '/aviator'
      preLoaderRoute: typeof AviatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  ActivityRoute: ActivityRoute,
  AviatorRoute: AviatorRoute,
  DepositRoute: DepositRoute,
  LoginRoute: LoginRoute,
  PromotionRoute: PromotionRoute,
  RegisterRoute: RegisterRoute,
  VipRoute: VipRoute,
  WalletRoute: WalletRoute,
  WingoRoute: WingoRoute,
  WithdrawRoute: WithdrawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
